# Using a while loop, print 5 random numbers between 0 and 99 (inclusive).
# The code below shows an example of how to begin solving this exercise.

# numbers = []

# while <condition>
#  # ...
# end

# Example output (your numbers will most likely be different):

# 62
# 96
# 31
# 16
# 36

# The method Kernel#rand does a nice job of returning a random number. 

# ANSWER:

numbers = []

while numbers.size < 5
  numbers << rand(100)
end

puts numbers

puts "####"

# DISCUSSION:


# Kernel#rand(max) returns a random integer greater than 0, and one less the parameter max (excluding).

# To print 5 random numbers between 0 and 99 using a while loop and the given empty array - we can use
# the array #size method to define the condition for the while loop. We know that a while loop executes any code
# within the loop until the condition no longer evaluates true. Line 196 comapres the size of the array and
# the value 5 being the number of elements needed to be generated by the #rand. In line 197, the #rand generates
# a random number between 0 and 100 while the shovel operator appends the generated number to the array numbers, causing
# the numbers.size to increase by 1. The while loop executes again, until the conditional statement is no longer true
# and exits the loop. The program continues by printing numbers on line 200.

####
